In [1]:
import sys
sys.path.insert(0, r"D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1")

from db.connection import init_db
from db.repositories.detection_repo import DetectionRepository
from feature_extraction2.sliding_window import SlidingWindow
from datetime import datetime


#  INITIALISATION DB (OBLIGATOIRE)
init_db()

detection_repo = DetectionRepository()

sliding_window = SlidingWindow(
    detection_repository=detection_repo,
    window_duration=5.0,
    step=1.0
)
for window_df in sliding_window.generate(
    camera_ids=[1],
    start_time=datetime(2026, 1, 16, 18, 36, 35),
    end_time=datetime(2026, 1, 16, 18, 38, 35)
):
    print(window_df)

D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1\db\repositories\detection_repo.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

In [3]:
window_df

NameError: name 'window_df' is not defined

Ce code permet de tester toutes les extractions de caractéristique 
Très important

In [2]:
# ==========================================================
# IMPORTS & PATH
# ==========================================================
import sys
sys.path.insert(0, r"D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1")

from datetime import datetime

from db.connection import init_db
from db.repositories.detection_repo import DetectionRepository

from feature_extraction2.sliding_window import SlidingWindow
from feature_extraction2.human_features import HumanPresenceFeatures
from feature_extraction2.epi_features import EPIFeatures
from feature_extraction2.machine_features import MachineVehicleFeatures
from feature_extraction2.proximity_features import ProximityFeatures
from feature_extraction2.temporal_dynamics_features import TemporalDynamicsFeatures

from system_automatic.analyzer import Analyzer
from system_automatic.risk_engine import RiskEngine




from db.repositories.zone_repo import ZoneRepository
from db.repositories.camera_calibration_repo import CameraCalibrationRepository
from db.repositories.camera_repo import CameraRepository
from feature_extraction2.zone_features import ZoneFeatures
from feature_extraction2.activity_stability_features import ActivityStabilityFeatures
from feature_extraction2.activity_transition_features import ActivityTransitionFeatures
from feature_extraction2.activity_stability_features import ActivityStabilityFeatures
from feature_extraction2.real_time_hse_analyzer import RealTimeHSEAnalyzer
from feature_extraction2.behavior_analyzer import BehaviorAnalyzer
import importlib
from db.repositories import camera_calibration_repo
importlib.reload(camera_calibration_repo)

# ==========================================================
# INITIALISATION DB (OBLIGATOIRE) ET REQUETTE
# ==========================================================
init_db()

detection_repo = DetectionRepository()


zone_repo = ZoneRepository()
calib_repo = CameraCalibrationRepository()

analyzer = BehaviorAnalyzer(history_size=30)


# ==========================================================
# SLIDING WINDOW
# ==========================================================
sliding_window = SlidingWindow(
    detection_repository=detection_repo,
    window_duration=5.0,   # fenêtre de 5 secondes
    step=1.0               # glissement de 1 seconde
)


# ==========================================================
# FEATURE EXTRACTORS ( NE PAS METTRE DANS LA BOUCLE)
# ==========================================================
human_extractor = HumanPresenceFeatures(
    image_width=1920,
    image_height=1080,
    stationary_threshold=2.0
)

epi_extractor = EPIFeatures(
    window_duration=5.0,
    persistent_threshold=3
)

machine_extractor = MachineVehicleFeatures(
    window_duration=5.0
)

proximity_extractor = ProximityFeatures(
    window_duration=5.0,
    danger_distance_pp=100,
    danger_distance_pm=150
)

temporal_extractor = TemporalDynamicsFeatures(window_duration=5.0)




stability_extractor = ActivityStabilityFeatures(history_size=5)


# ==========================================================
# PARAMÈTRES DE TEST
# ==========================================================
START_TIME = datetime(2026, 1, 18, 20, 31, 40)
END_TIME   = datetime(2026, 1, 18, 20, 32, 25)

MAX_WINDOWS = 10   # pour ne pas inonder le notebook


# ==========================================================
# TEST PIPELINE COMPLET
# ==========================================================
#zones = zone_repo.get_active_zones_by_plan(plan_id=1)
#H = calib_repo.get_active_calibration(camera_id=1, plan_id=1)
camera_repo = CameraRepository()
calib_repo = CameraCalibrationRepository()

current_camera_id = None
zone_extractor = None

current_camera_id = None


# BOUCLE DE TEST
for i, (window_df, win_start, win_end) in enumerate(sliding_window.generate(camera_ids=[1],
        start_time=START_TIME,
        end_time=END_TIME)):
    
    cam_id = int(window_df["camera_id"].iloc[0])

    if cam_id != current_camera_id:
        # A. Récupérer la config caméra (pour avoir le plan_id)
        cam_info = camera_repo.get_camera_config(cam_id)
        
        if cam_info is not None:
            plan_id = int(cam_info['plan_id'])
            
            # B. Utiliser le plan_id pour récupérer la matrice H
            H = calib_repo.get_active_calibration(cam_id, plan_id)
            
            if H is not None:
                # C. Mettre à jour les zones pour le bon plan
                zones = zone_repo.get_active_zones_by_plan(plan_id=plan_id)
                
                # D. Ré-instancier l'extracteur de zone
                zone_extractor = ZoneFeatures(
                    zones=zones,
                    homography=H,
                    window_duration=5.0
                )
                current_camera_id = cam_id
                print(f" Calibrage et Zones mis à jour pour Caméra {cam_id} (Plan {plan_id})")

    


    if i >= MAX_WINDOWS:
        break

    print("\n" + "=" * 60)
    print(f"🪟 FENÊTRE {i}")
    print(f"Période : {win_start} → {win_end}")
    print("=" * 60)

    print(f"Nombre total de détections : {len(window_df)}")

    if window_df.empty:
        print(" Fenêtre vide (pas de détection dans cet intervalle)")
        continue

    print(f"Nombre total de détections trouvées : {len(window_df)}")   

    # ------------------------------------------------------
    # DEBUG TEMPOREL
    # ------------------------------------------------------
    print(
        " Intervalle temporel :",
        window_df["timestamp"].min(),
        "→",
        window_df["timestamp"].max()
    )

    # ------------------------------------------------------
    # OBJETS DÉTECTÉS
    # ------------------------------------------------------
    print("\n Objets détectés :")
    print(window_df["object_class"].value_counts())

    # ======================================================
    # EPI FEATURES
    # ======================================================
    print("\n EPI FEATURES")
    epi_features = epi_extractor.extract(window_df)

    for k, v in epi_features.items():
        print(f"{k:<35} : {v}")

    # ======================================================
    # MACHINE / VEHICLE FEATURES
    # ======================================================
    print("\n MACHINE / VEHICLE FEATURES")
    machine_features = machine_extractor.extract(window_df)

    for k, v in machine_features.items():
        print(f"{k:<35} : {v}")


    # ======================================================
    # Proximité
    # ======================================================
    print("\n Proximité PERSONNE / VEHICLE FEATURES")
    proximity_features  = proximity_extractor.extract(window_df)

    for k, v in proximity_features .items():
        print(f"{k:<35} : {v}")



    # ======================================================
    # temporel
    # ======================================================
    print("\n Temporel")
    temporal_features = temporal_extractor.extract(window_df)
    for k,v in temporal_features.items():
        print(f"{k}: {v}")



    # ======================================================
    # Zone 
    # ======================================================
    print("\n Zone et homographie")
    zone_features = zone_extractor.extract(window_df)
    for k,v in zone_features.items():
        print(f"{k}: {v}")

D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1\db\repositories\detection_repo.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)
D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1\db\repositories\camera_repo.py:39: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=[camera_id])

 Calibrage et Zones mis à jour pour Caméra 1 (Plan 1)

============================================================
🪟 FENÊTRE 0
Période : 2026-01-18 20:31:40 → 2026-01-18 20:31:45
============================================================
Nombre total de détections : 111
Nombre total de détections trouvées : 111
 Intervalle temporel : 2026-01-18 20:31:40 → 2026-01-18 20:31:44

 Objets détectés :
object_class
safety_vest    59
person         45
hardhat         6
safety_cone     1
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 148.90453356551404
std_person_person_distance          : 140.8610659878604
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.2660300734879252
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 540
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 20.0816690314736
std_person_speed: 13.906114173180878
direction_variance: 4719.832666305411
track_lifetime_mean: 4.0
sudden_stop_events: 1
erratic_motion_score: 65634.53193595177
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 52.72758444444444
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 1
Période : 2026-01-18 20:31:41 → 2026-01-18 20:31:46
============================================================
Nombre total de détections : 111
Nombre total de détections trouvées : 111
 Intervalle temporel : 2026-01-18 20:31:41 → 2026-01-18 20:31:45

 Objets détectés :
object_class
safety_vest    60
person         44
hardhat         6
safety_cone     1
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 0.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.3333333333333333
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 156.94394747289837
std_person_person_distance          : 138.29808479231667
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.32520762598686787
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 478
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 19.873782662849173
std_person_speed: 15.981168552476028
direction_variance: 4527.510388522647
track_lifetime_mean: 4.0
sudden_stop_events: 2
erratic_motion_score: 72354.90664206665
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 54.454152272727285
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 2
Période : 2026-01-18 20:31:42 → 2026-01-18 20:31:47
============================================================
Nombre total de détections : 101
Nombre total de détections trouvées : 101
 Intervalle temporel : 2026-01-18 20:31:42 → 2026-01-18 20:31:46

 Objets détectés :
object_class
safety_vest    55
person         39
hardhat         7
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 158.09736230601013
std_person_person_distance          : 136.78953442700467
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.32520762598686787
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 361
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 16.360878309977895
std_person_speed: 13.759152392369689
direction_variance: 7594.897773877879
track_lifetime_mean: 3.5
sudden_stop_events: 2
erratic_motion_score: 104499.35587525505
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 56.49087435897436
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 3
Période : 2026-01-18 20:31:43 → 2026-01-18 20:31:48
============================================================
Nombre total de détections : 92
Nombre total de détections trouvées : 92
 Intervalle temporel : 2026-01-18 20:31:43 → 2026-01-18 20:31:47

 Objets détectés :
object_class
safety_vest    50
person         32
hardhat        10
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 150.59157525659253
std_person_person_distance          : 136.83331438224673
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.32520762598686787
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 249
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 17.873067525129844
std_person_speed: 15.030031062996848
direction_variance: 14542.594041119824
track_lifetime_mean: 3.0
sudden_stop_events: 2
erratic_motion_score: 218575.64017458382
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 59.8113
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 4
Période : 2026-01-18 20:31:44 → 2026-01-18 20:31:49
============================================================
Nombre total de détections : 67
Nombre total de détections trouvées : 67
 Intervalle temporel : 2026-01-18 20:31:44 → 2026-01-18 20:31:48

 Objets détectés :
object_class
safety_vest    40
person         21
hardhat         6
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 124.3039080991212
std_person_person_distance          : 131.78285556135245
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.32520762598686787
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 120
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 12.295104751742025
std_person_speed: 9.02920084517124
direction_variance: 11207.106432058892
track_lifetime_mean: 2.0
sudden_stop_events: 0
erratic_motion_score: 101191.2148682702
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 62.88353333333333
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 5
Période : 2026-01-18 20:31:45 → 2026-01-18 20:31:50
============================================================
Nombre total de détections : 51
Nombre total de détections trouvées : 51
 Intervalle temporel : 2026-01-18 20:31:45 → 2026-01-18 20:31:49

 Objets détectés :
object_class
safety_vest    32
person         13
hardhat         6
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 87.4590237553187
std_person_person_distance          : 120.23608008754229
avg_person_machine_distance         : 0.0
min_person_person_distance          : 0.32520762598686787
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 56
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 18.622434992069657
std_person_speed: 8.828564228040733
direction_variance: 429.13833674102966
track_lifetime_mean: 2.0
sudden_stop_events: 0
erratic_motion_score: 3788.6753686327525
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 68.3433
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 6
Période : 2026-01-18 20:31:46 → 2026-01-18 20:31:51
============================================================
Nombre total de détections : 38
Nombre total de détections trouvées : 38
 Intervalle temporel : 2026-01-18 20:31:46 → 2026-01-18 20:31:50

 Objets détectés :
object_class
safety_vest    23
person          8
hardhat         7
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 25.709539397096865
std_person_person_distance          : 25.50906833902089
avg_person_machine_distance         : 0.0
min_person_person_distance          : 2.313422140466385
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 28
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 27.45099922011039
std_person_speed: 0.0
direction_variance: 0.0
track_lifetime_mean: 1.0
sudden_stop_events: 0
erratic_motion_score: 0.0
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 72.92711249999999
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 7
Période : 2026-01-18 20:31:47 → 2026-01-18 20:31:52
============================================================
Nombre total de détections : 30
Nombre total de détections trouvées : 30
 Intervalle temporel : 2026-01-18 20:31:47 → 2026-01-18 20:31:51

 Objets détectés :
object_class
safety_vest    18
hardhat         6
person          6
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 46.817382723073514
std_person_person_distance          : 33.42436615770881
avg_person_machine_distance         : 0.0
min_person_person_distance          : 3.2575014965461233
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 14
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 0.0
std_person_speed: 0.0
direction_variance: 0.0
track_lifetime_mean: 0.0
sudden_stop_events: 0
erratic_motion_score: 0.0
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 3.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 70.60388333333334
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 8
Période : 2026-01-18 20:31:48 → 2026-01-18 20:31:53
============================================================
Nombre total de détections : 20
Nombre total de détections trouvées : 20
 Intervalle temporel : 2026-01-18 20:31:48 → 2026-01-18 20:31:52

 Objets détectés :
object_class
safety_vest    13
person          5
hardhat         2
Name: count, dtype: int64

 EPI FEATURES
helmet_compliance_ratio             : 1.0
vest_compliance_ratio               : 1.0
mask_compliance_ratio               : 0.0
avg_epi_compliance                  : 0.6666666666666666
num_no_helmet_events                : 0
num_no_vest_events                  : 0
num_no_mask_events                  : 0
epi_violation_duration              : 0.0
persistent_epi_violation            : 0

 MACHINE / VEHICLE FEATURES
num_machines_avg                    : 0.0
machine_presence_ratio              : 0.0
unique_machine_tracks               : 0
machine_type_ratio                  : 0.0
co_presence_person_machine          : 0.0
machine_dominance_ratio             : 0.0
machine_only_duration               : 0.0

 Proximité PERSONNE / VEHICLE FEATURES
avg_person_person_distance          : 52.78591228310229
std_person_person_distance          : 57.32476099598347
avg_person_machine_distance         : 0.0
min_person_person_distance          : 1.8342295630591077
min_person_machine_distance         : 0.0
dangerous_proximity_frames          : 6
bbox_overlap_person_machine         : 0
time_near_machine                   : 0.0
num_machine_interactions            : 0

 Temporel
avg_person_speed: 11.645448531615274
std_person_speed: 0.0
direction_variance: 0.0
track_lifetime_mean: 1.0
sudden_stop_events: 0
erratic_motion_score: 0.0
high_speed_near_machine: 0

 Zone et homographie
num_persons_in_zone: 2.0
num_people_in_high_risk_zone: 0.0
proportion_time_in_high_risk_zone: 0.0
multiple_zone_exposure: 0.0
avg_person_height: 61.85596
time_near_machine: 0.0
num_machine_interactions: 0.0
motion_consistency: 0.0
activity_persistence_score: 0.0
zone_type: 6.0
zone_risk_level: 1.0

============================================================
🪟 FENÊTRE 9
Période : 2026-01-18 20:31:49 → 2026-01-18 20:31:54
============================================================
Nombre total de détections : 16
Nombre total de détections trouvées : 16
 Intervalle temporel : 2026-01-18 20:31:49 → 2026-01-18 20:31:52

 Objets détectés :
object_class
safety_vest    9
person         5
hardhat        2

In [3]:
print(hasattr(calib_repo, '_fetch_from_db'))

True

In [3]:
# ==========================================================
# PARAMÈTRES DE TEST
# ==========================================================
START_TIME = datetime(2026, 2, 24, 20, 19, 6)
END_TIME   = datetime(2026, 2, 24, 20, 19, 27)

MAX_WINDOWS = 10   # pour ne pas inonder le notebook


from feature_extraction2.pipeline import extract_features_pipeline
import pandas as pd

df_all, df_ml = extract_features_pipeline(
    sliding_window=sliding_window,
    behavior_extractor=analyzer,
    human_extractor=human_extractor,
    epi_extractor=epi_extractor,
    machine_extractor=machine_extractor,
    proximity_extractor=proximity_extractor,
    temporal_extractor=temporal_extractor,
    zone_extractor=zone_extractor,
    stability_extractor=stability_extractor,
    camera_ids=[1],
    start_time=START_TIME,
    end_time=END_TIME,
    max_windows=100
)

df_all=pd.DataFrame(df_all)
df_ml=pd.DataFrame(df_ml)

print("\n ALL FEATURES")
# Désactiver la limite de lignes


df_all

D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1\db\repositories\detection_repo.py:42: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn, params=params)

 ALL FEATURES

,window_index,window_start,window_end,camera_id,num_detections,avg_num_persons,max_num_persons,unique_person_tracks,person_density,person_presence_ratio,...,high_speed_near_machine,motion_consistency,activity_persistence_score,num_persons_in_zone,num_people_in_high_risk_zone,proportion_time_in_high_risk_zone,multiple_zone_exposure,zone_type,zone_risk_level,motion_stability_score
0,0,2026-02-24 20:19:06,2026-02-24 20:19:11,1,23,1.333333,2,2,6.430041e-07,1.0,...,0,0.500000,0.500000,2.0,0.0,0.0,0.0,6.0,1.0,0.500000
1,1,2026-02-24 20:19:07,2026-02-24 20:19:12,1,23,1.333333,2,3,6.430041e-07,1.0,...,0,0.812777,1.000000,3.0,0.0,0.0,0.0,6.0,1.0,0.848122
2,2,2026-02-24 20:19:08,2026-02-24 20:19:13,1,19,1.333333,2,3,6.430041e-07,1.0,...,0,0.846960,1.000000,3.0,0.0,0.0,0.0,6.0,1.0,0.855553
3,3,2026-02-24 20:19:09,2026-02-24 20:19:14,1,17,1.500000,2,2,7.233796e-07,1.0,...,0,0.867388,0.932689,2.0,0.0,0.0,0.0,6.0,1.0,0.865738
4,4,2026-02-24 20:19:10,2026-02-24 20:19:15,1,17,1.500000,2,2,7.233796e-07,1.0,...,0,0.881348,0.924514,2.0,0.0,0.0,0.0,6.0,1.0,0.874691
5,5,2026-02-24 20:19:11,2026-02-24 20:19:16,1,17,1.500000,2,2,7.233796e-07,1.0,...,0,0.923340,0.924514,2.0,0.0,0.0,0.0,6.0,1.0,1.000000
6,6,2026-02-24 20:19:12,2026-02-24 20:19:17,1,8,2.000000,2,2,9.645062e-07,1.0,...,0,0.500000,0.815609,2.0,0.0,0.0,0.0,6.0,1.0,1.000000
7,7,2026-02-24 20:19:15,2026-02-24 20:19:20,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,0.183503,0.759747,1.0,0.0,0.0,0.0,6.0,1.0,1.000000
8,8,2026-02-24 20:19:16,2026-02-24 20:19:21,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,0.000000,0.727714,1.0,0.0,0.0,0.0,6.0,1.0,1.000000
9,9,2026-02-24 20:19:17,2026-02-24 20:19:22,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,0.000000,0.714286,1.0,0.0,0.0,0.0,6.0,1.0,1.000000
10,10,2026-02-24 20:19:18,2026-02-24 20:19:23,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,1.000000,0.714286,1.0,0.0,0.0,0.0,6.0,1.0,1.000000
11,11,2026-02-24 20:19:19,2026-02-24 20:19:24,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,1.000000,1.000000,1.0,0.0,0.0,0.0,6.0,1.0,1.000000
12,12,2026-02-24 20:19:22,2026-02-24 20:19:27,1,1,1.000000,1,1,4.822531e-07,1.0,...,0,1.000000,1.000000,1.0,0.0,0.0,0.0,6.0,1.0,1.000000

In [ ]:
df_ml.head()

In [4]:
from datetime import datetime, timedelta

# 1. Initialisation
analyzer = Analyzer()
engine = RiskEngine('../system_automatic/hse_rules.json')

# 2. Simulation de cycle
# Dans ton mode 'cycle' :
def run_loop():
    # Décalage de 5 minutes
    t_delta = timedelta(minutes=5)
    
    # A : Récupérer la borne finale
    end_time = analyzer.get_last_detection_timestamp()
    start_time = end_time - t_delta
    
    # B : Extraction
    df_batch = analyzer.fetch_recent_data(start_time, end_time)
    
    if not df_batch.empty:
        # C : Prédiction ML (supposons que ton modèle est chargé)
        # df_batch['activity_pred'] = model.predict(df_batch[ML_FEATURES])
        
        # D : Analyse HSE
        df_analyzed = engine.process_dataframe(df_batch)
        
        # E : Mise à jour du state
        analyzer.update_last_timestamp(df_analyzed)
        
        return df_analyzed
    return None

In [5]:
analyzer = Analyzer()
end_time = analyzer.get_last_detection_timestamp()
end_time

D:\ETUDEµ\CITE\ETAPE4\PROJET DE FIN DE SESSION\TOURMANT 1\db\repositories\detection_repo.py:85: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn)

datetime.datetime(2026, 3, 29, 15, 45, 43)

In [3]:
# Désactiver la limite de lignes
pd.set_option('display.max_rows', None)

# Désactiver la limite de colonnes
pd.set_option('display.max_columns', None)

# Désactiver la limite de largeur de colonne (pour afficher tout le texte)
pd.set_option('display.max_colwidth', None)
df_ml

,avg_num_persons,max_num_persons,unique_person_tracks,person_density,person_presence_ratio,avg_epi_compliance,helmet_compliance_ratio,vest_compliance_ratio,num_no_helmet_events,num_no_vest_events,num_machines_avg,machine_presence_ratio,unique_machine_tracks,co_presence_person_machine,dangerous_proximity_frames,min_person_machine_distance,avg_person_speed,std_person_speed,sudden_stop_events,erratic_motion_score,direction_variance,zone_type,zone_risk_level,num_persons_in_zone,num_people_in_high_risk_zone,proportion_time_in_high_risk_zone,multiple_zone_exposure,avg_person_height,time_near_machine,num_machine_interactions,motion_consistency,activity_persistence_score
0,1.333333,2,2,6.430041e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,31,0.0,62.321627,19.65604,0,0.358152,0.018221,6.0,1.0,2.0,0.0,0.0,0.0,51.198789,0.0,0.0,0.500000,0.500000
1,1.333333,2,3,6.430041e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,32,0.0,42.665587,0.00000,0,0.000000,0.000000,6.0,1.0,3.0,0.0,0.0,0.0,49.289322,0.0,0.0,0.812777,1.000000
2,1.333333,2,3,6.430041e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,32,0.0,52.323205,0.00000,0,0.000000,0.000000,6.0,1.0,3.0,0.0,0.0,0.0,38.612367,0.0,0.0,0.846960,1.000000
3,1.500000,2,2,7.233796e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,24,0.0,52.323205,0.00000,0,0.000000,0.000000,6.0,1.0,2.0,0.0,0.0,0.0,34.525888,0.0,0.0,0.867388,0.932689
4,1.500000,2,2,7.233796e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,24,0.0,52.323205,0.00000,0,0.000000,0.000000,6.0,1.0,2.0,0.0,0.0,0.0,34.525888,0.0,0.0,0.881348,0.924514
5,1.500000,2,2,7.233796e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,24,0.0,52.323205,0.00000,0,0.000000,0.000000,6.0,1.0,2.0,0.0,0.0,0.0,34.525888,0.0,0.0,0.923340,0.924514
6,2.000000,2,2,9.645062e-07,1.0,0.666667,1.0,1.0,0,0,0.0,0.0,0,0.0,10,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,2.0,0.0,0.0,0.0,36.600620,0.0,0.0,0.500000,0.815609
7,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,61.630400,0.0,0.0,0.183503,0.759747
8,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,61.630400,0.0,0.0,0.000000,0.727714
9,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,61.630400,0.0,0.0,0.000000,0.714286
10,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,61.630400,0.0,0.0,1.000000,0.714286
11,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,61.630400,0.0,0.0,1.000000,1.000000
12,1.000000,1,1,4.822531e-07,1.0,0.000000,0.0,0.0,0,0,0.0,0.0,0,0.0,0,0.0,0.000000,0.00000,0,0.000000,0.000000,6.0,1.0,1.0,0.0,0.0,0.0,352.000000,0.0,0.0,1.000000,1.000000

In [4]:
df_ml.columns

Index(['avg_num_persons', 'max_num_persons', 'unique_person_tracks',
       'person_density', 'person_presence_ratio', 'avg_epi_compliance',
       'helmet_compliance_ratio', 'vest_compliance_ratio',
       'num_no_helmet_events', 'num_no_vest_events', 'num_machines_avg',
       'machine_presence_ratio', 'unique_machine_tracks',
       'co_presence_person_machine', 'dangerous_proximity_frames',
       'min_person_machine_distance', 'avg_person_speed', 'std_person_speed',
       'sudden_stop_events', 'erratic_motion_score', 'direction_variance',
       'zone_type', 'zone_risk_level', 'num_persons_in_zone',
       'num_people_in_high_risk_zone', 'proportion_time_in_high_risk_zone',
       'multiple_zone_exposure', 'avg_person_height', 'time_near_machine',
       'num_machine_interactions', 'motion_consistency',
       'activity_persistence_score'],
      dtype='object')

In [3]:
df_all.columns

Index(['window_index', 'window_start', 'window_end', 'camera_id',
       'num_detections', 'avg_num_persons', 'max_num_persons',
       'unique_person_tracks', 'person_density', 'person_presence_ratio',
       'num_person_entries', 'avg_person_height', 'stationary_person_ratio',
       'crowding_score', 'helmet_compliance_ratio', 'vest_compliance_ratio',
       'mask_compliance_ratio', 'avg_epi_compliance', 'num_no_helmet_events',
       'num_no_vest_events', 'num_no_mask_events', 'epi_violation_duration',
       'persistent_epi_violation', 'num_machines_avg',
       'machine_presence_ratio', 'unique_machine_tracks', 'machine_type_ratio',
       'co_presence_person_machine', 'machine_dominance_ratio',
       'machine_only_duration', 'avg_person_person_distance',
       'std_person_person_distance', 'avg_person_machine_distance',
       'min_person_person_distance', 'min_person_machine_distance',
       'dangerous_proximity_frames', 'bbox_overlap_person_machine',
       'time_near_machine', 'num_machine_interactions', 'avg_person_speed',
       'std_person_speed', 'direction_variance', 'track_lifetime_mean',
       'sudden_stop_events', 'erratic_motion_score', 'high_speed_near_machine',
       'motion_consistency', 'activity_persistence_score',
       'num_persons_in_zone', 'num_people_in_high_risk_zone',
       'proportion_time_in_high_risk_zone', 'multiple_zone_exposure',
       'zone_type', 'zone_risk_level', 'motion_stability_score'],
      dtype='object')

In [7]:
df_ml.shape

(10, 25)

Prédiction de l'activité

In [6]:
import joblib
from activity_prediction import ActivityPredictor


# charger modèle
model = joblib.load("../dataset machine Learning/model_hse_v1.pkl")

# créer predictor
predictor = ActivityPredictor(model)

# prédire activités
df_ml = predictor.predict(df_ml)
df_all["activity_pred"] = df_ml["activity_pred"]
df_all["activity_confidence"] = df_ml["activity_confidence"]

print("\n========== DF_ML AVEC ACTIVITÉS ==========")
print(df_ml.head())

print("\n========== DF_ALL AVEC ACTIVITÉS ==========")
print(df_all.head())

========== ACTIVITY PREDICTION ==========
Features utilisées par le modèle :
['avg_num_persons' 'max_num_persons' 'unique_person_tracks'
 'person_density' 'person_presence_ratio' 'avg_epi_compliance'
 'helmet_compliance_ratio' 'vest_compliance_ratio' 'num_no_helmet_events'
 'num_no_vest_events' 'num_machines_avg' 'machine_presence_ratio'
 'unique_machine_tracks' 'co_presence_person_machine'
 'dangerous_proximity_frames' 'min_person_machine_distance'
 'avg_person_speed' 'std_person_speed' 'sudden_stop_events'
 'erratic_motion_score' 'direction_variance' 'num_persons_in_zone'
 'num_people_in_high_risk_zone' 'proportion_time_in_high_risk_zone'
 'multiple_zone_exposure' 'avg_person_height' 'time_near_machine'
 'num_machine_interactions' 'motion_consistency'
 'activity_persistence_score' 'zone_type' 'zone_risk_level']

Activités détectées :
activity_pred
1    10
3     3
Name: count, dtype: int64

========== DF_ML AVEC ACTIVITÉS ==========
   avg_num_persons  max_num_persons  unique_person_tracks  person_density  \
0         1.333333                2                     2    6.430041e-07
1         1.333333                2                     3    6.430041e-07
2         1.333333                2                     3    6.430041e-07
3         1.500000                2                     2    7.233796e-07
4         1.500000                2                     2    7.233796e-07

   person_presence_ratio  avg_epi_compliance  helmet_compliance_ratio  \
0                    1.0            0.666667                      1.0
1                    1.0            0.666667                      1.0
2                    1.0            0.666667                      1.0
3                    1.0            0.666667                      1.0
4                    1.0            0.666667                      1.0

   vest_compliance_ratio  num_no_helmet_events  num_no_vest_events  ...  \
0                    1.0                     0                   0  ...
1                    1.0                     0                   0  ...
2                    1.0                     0                   0  ...
3                    1.0                     0                   0  ...
4                    1.0                     0                   0  ...

   num_people_in_high_risk_zone  proportion_time_in_high_risk_zone  \
0                           0.0                                0.0
1                           0.0                                0.0
2                           0.0                                0.0
3                           0.0                                0.0
4                           0.0                                0.0

   multiple_zone_exposure  avg_person_height  time_near_machine  \
0                     0.0          51.198789                0.0
1                     0.0          49.289322                0.0
2                     0.0          38.612367                0.0
3                     0.0          34.525888                0.0
4                     0.0          34.525888                0.0

   num_machine_interactions  motion_consistency  activity_persistence_score  \
0                       0.0            0.500000                    0.500000
1                       0.0            0.812777                    1.000000
2                       0.0            0.846960                    1.000000
3                       0.0            0.867388                    0.932689
4                       0.0            0.881348                    0.924514

   activity_pred  activity_confidence
0              1             0.882520
1              1             0.911952
2              1             0.911952
3              1             0.911952
4              1             0.911952

[5 rows x 34 columns]

========== DF_ALL AVEC ACTIVITÉS ==========
   window_index        window_start          window_end  camera_id  \
0             0 2026-02-24 20:19:06 2026-02-24 20:19:11          1
1             1 2026-02-24 20:19:07 2026-02-24 20:19:12          1
2             2 2026-02-24 20:19:08 2026-02-24 20:19:13          1
3             3 2026-02-24 20:19:09 2026-02-24 20:19:14          1
4             4 2026-02-24 20:19:10 2026-02-24 20:19:15          1

   num_detections  avg_num_persons  max_num_persons  unique_person_tracks  \
0              23         1.333333                2                     2
1              23         1.333333                2                     3
2              19         1.333333                2                     3
3              17         1.500000                2                     2
4              17         1.500000                2                     2

   person_density  person_presence_ratio  ...  activity_persistence_score  \
0    6.430041e-07                    1.0  ...                    0.500000
1    6.430041e-07                    1.0  ...                    1.000000
2    6.430041e-07                    1.0  ...                    1.000000
3    7.233796e-07                    1.0  ...                    0.932689
4    7.233796e-07                    1.0  ...                    0.924514

   num_persons_in_zone  num_people_in_high_risk_zone  \
0                  2.0                           0.0
1                  3.0                           0.0
2                  3.0                           0.0
3                  2.0                           0.0
4                  2.0                           0.0

   proportion_time_in_high_risk_zone  multiple_zone_exposure  zone_type  \
0                                0.0                     0.0        6.0
1                                0.0                     0.0        6.0
2                                0.0                     0.0        6.0
3                                0.0                     0.0        6.0
4                                0.0                     0.0        6.0

   zone_risk_level  motion_stability_score  activity_pred  activity_confidence
0              1.0                0.500000              1             0.882520
1              1.0                0.848122              1             0.911952
2              1.0                0.855553              1             0.911952
3              1.0                0.865738              1             0.911952
4              1.0                0.874691              1             0.911952

[5 rows x 57 columns]

c:\Users\MEHOUN MARTINIEN\AppData\Local\Programs\Python\Python312\Lib\pickle.py:1760: UserWarning: [16:00:23] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\data\../common/error_msg.h:83: If you are loading a serialized model (like pickle in Python, RDS in R) or
configuration generated by an older version of XGBoost, please export the model by calling
`Booster.save_model` from that version first, then load it back in current version. See:

    https://xgboost.readthedocs.io/en/stable/tutorials/saving_model.html

for more details about differences between saving model and serializing.

  setstate(state)

In [7]:
import pandas as pd
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
df_all

,window_index,window_start,window_end,camera_id,num_detections,avg_num_persons,max_num_persons,unique_person_tracks,person_density,person_presence_ratio,num_person_entries,avg_person_height,stationary_person_ratio,crowding_score,helmet_compliance_ratio,vest_compliance_ratio,mask_compliance_ratio,avg_epi_compliance,num_no_helmet_events,num_no_vest_events,num_no_mask_events,epi_violation_duration,persistent_epi_violation,num_machines_avg,machine_presence_ratio,unique_machine_tracks,machine_type_ratio,co_presence_person_machine,machine_dominance_ratio,machine_only_duration,avg_person_person_distance,std_person_person_distance,avg_person_machine_distance,min_person_person_distance,min_person_machine_distance,dangerous_proximity_frames,bbox_overlap_person_machine,time_near_machine,num_machine_interactions,avg_person_speed,std_person_speed,direction_variance,track_lifetime_mean,sudden_stop_events,erratic_motion_score,high_speed_near_machine,motion_consistency,activity_persistence_score,num_persons_in_zone,num_people_in_high_risk_zone,proportion_time_in_high_risk_zone,multiple_zone_exposure,zone_type,zone_risk_level,motion_stability_score,activity_pred,activity_confidence
0,0,2026-02-24 20:19:06,2026-02-24 20:19:11,1,23,1.333333,2,2,6.430041e-07,1.0,0,51.198789,0.0,0.266667,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,56.862916,32.667759,0.0,11.785504,0.0,31,0,0.0,0.0,62.321627,19.65604,0.018221,2.0,0,0.358152,0,0.500000,0.500000,2.0,0.0,0.0,0.0,6.0,1.0,0.500000,1,0.882520
1,1,2026-02-24 20:19:07,2026-02-24 20:19:12,1,23,1.333333,2,3,6.430041e-07,1.0,0,49.289322,0.0,0.266667,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,54.444302,31.051213,0.0,7.912670,0.0,32,0,0.0,0.0,42.665587,0.00000,0.000000,1.0,0,0.000000,0,0.812777,1.000000,3.0,0.0,0.0,0.0,6.0,1.0,0.848122,1,0.911952
2,2,2026-02-24 20:19:08,2026-02-24 20:19:13,1,19,1.333333,2,3,6.430041e-07,1.0,1,38.612367,0.0,0.266667,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,52.021529,31.115072,0.0,2.473194,0.0,32,0,0.0,0.0,52.323205,0.00000,0.000000,1.0,0,0.000000,0,0.846960,1.000000,3.0,0.0,0.0,0.0,6.0,1.0,0.855553,1,0.911952
3,3,2026-02-24 20:19:09,2026-02-24 20:19:14,1,17,1.500000,2,2,7.233796e-07,1.0,0,34.525888,0.0,0.300000,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,50.044830,34.162280,0.0,2.473194,0.0,24,0,0.0,0.0,52.323205,0.00000,0.000000,1.0,0,0.000000,0,0.867388,0.932689,2.0,0.0,0.0,0.0,6.0,1.0,0.865738,1,0.911952
4,4,2026-02-24 20:19:10,2026-02-24 20:19:15,1,17,1.500000,2,2,7.233796e-07,1.0,0,34.525888,0.0,0.300000,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,50.044830,34.162280,0.0,2.473194,0.0,24,0,0.0,0.0,52.323205,0.00000,0.000000,1.0,0,0.000000,0,0.881348,0.924514,2.0,0.0,0.0,0.0,6.0,1.0,0.874691,1,0.911952
5,5,2026-02-24 20:19:11,2026-02-24 20:19:16,1,17,1.500000,2,2,7.233796e-07,1.0,0,34.525888,0.0,0.300000,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,50.044830,34.162280,0.0,2.473194,0.0,24,0,0.0,0.0,52.323205,0.00000,0.000000,1.0,0,0.000000,0,0.923340,0.924514,2.0,0.0,0.0,0.0,6.0,1.0,1.000000,1,0.911952
6,6,2026-02-24 20:19:12,2026-02-24 20:19:17,1,8,2.000000,2,2,9.645062e-07,1.0,0,36.600620,0.0,0.400000,1.0,1.0,0.0,0.666667,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,46.114418,29.184007,0.0,2.473194,0.0,10,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,0.500000,0.815609,2.0,0.0,0.0,0.0,6.0,1.0,1.000000,3,0.347333
7,7,2026-02-24 20:19:15,2026-02-24 20:19:20,1,1,1.000000,1,1,4.822531e-07,1.0,1,61.630400,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,0.183503,0.759747,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,1,0.447128
8,8,2026-02-24 20:19:16,2026-02-24 20:19:21,1,1,1.000000,1,1,4.822531e-07,1.0,1,61.630400,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,0.000000,0.727714,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,1,0.443854
9,9,2026-02-24 20:19:17,2026-02-24 20:19:22,1,1,1.000000,1,1,4.822531e-07,1.0,1,61.630400,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,0.000000,0.714286,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,1,0.443854
10,10,2026-02-24 20:19:18,2026-02-24 20:19:23,1,1,1.000000,1,1,4.822531e-07,1.0,1,61.630400,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,1.000000,0.714286,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,1,0.447128
11,11,2026-02-24 20:19:19,2026-02-24 20:19:24,1,1,1.000000,1,1,4.822531e-07,1.0,1,61.630400,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,1.000000,1.000000,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,3,0.342736
12,12,2026-02-24 20:19:22,2026-02-24 20:19:27,1,1,1.000000,1,1,4.822531e-07,1.0,1,352.000000,0.0,0.200000,0.0,0.0,0.0,0.000000,0,0,0,0.0,0,0.0,0.0,0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0,0.000000,0.0,0,0,0.0,0.0,0.000000,0.00000,0.000000,0.0,0,0.000000,0,1.000000,1.000000,1.0,0.0,0.0,0.0,6.0,1.0,1.000000,3,0.342736

In [10]:

# --- Utilisation ---
if __name__ == "__main__":
    # 1. Charger ton dataframe (df) ici
    # 2. Initialiser l'engine
    engine = RiskEngine('../system_automatic/hse_rules.json')
    
    # 3. Transformer le dataframe
    df_analyzed = engine.process_dataframe(df_all)
    
    # Affichage des résultats critiques
    print(df_analyzed[['activity_pred', 'risk_score', 'risk_level', 'risk_messages']].head())

   activity_pred  risk_score risk_level  \
0              1         100   CRITIQUE
1              1         100   CRITIQUE
2              1         100   CRITIQUE
3              1         100   CRITIQUE
4              1         100   CRITIQUE

                                       risk_messages
0  ELEVE: ConformitÃ© EPI globale insuffisante. |...
1  ELEVE: ConformitÃ© EPI globale insuffisante. |...
2  ELEVE: ConformitÃ© EPI globale insuffisante. |...
3  ELEVE: ConformitÃ© EPI globale insuffisante. |...
4  ELEVE: ConformitÃ© EPI globale insuffisante. |...

In [12]:
df_analyzed[['activity_pred', 'risk_score', 'risk_level', 'risk_messages']]

,activity_pred,risk_score,risk_level,risk_messages
0,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
1,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
2,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
3,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
4,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
5,1,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
6,3,100,CRITIQUE,ELEVE: ConformitÃ© EPI globale insuffisante. |...
7,1,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...
8,1,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...
9,1,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...
10,1,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...
11,3,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...
12,3,100,CRITIQUE,CRITIQUE: Casque absent. Risque vital immÃ©dia...

In [3]:
import cv2
img = cv2.imread("utils/8-768x577.jpg")
cv2.imshow("img", img)
cv2.waitKey(0)

-1

**Option 1 — Homographie**

Principe

Tu relies l’image caméra au plan par une matrice 3×3

Cette matrice est calculée une fois par caméra

Données nécessaires (calibration)

Pour chaque caméra :

4 points minimum visibles :

(x_image, y_image) ↔ (x_plan, y_plan)

In [4]:
import numpy as np
import cv2

def compute_homography(pts_image, pts_plan):
    """
    pts_image : liste ou np.array Nx2 (pixels caméra)
    pts_plan  : liste ou np.array Nx2 (coordonnées plan)
    """

    # Conversion en numpy float32 (OBLIGATOIRE pour OpenCV)
    pts_image = np.array(pts_image, dtype=np.float32)
    pts_plan = np.array(pts_plan, dtype=np.float32)

    assert pts_image.shape == pts_plan.shape
    assert pts_image.shape[0] >= 4

    # Calcul de l'homographie
    H, mask = cv2.findHomography(
        pts_image,
        pts_plan,
        method=cv2.RANSAC,      # robuste aux erreurs
        ransacReprojThreshold=3.0
    )

    return H, mask

In [5]:
pts_image = [
    [305, 331],
    [193, 313],
    [331, 328],
    [476, 355]
]

pts_plan = [
    [12.0, 6.0],
    [10.0, 5.5],
    [13.2, 6.1],
    [15.0, 7.0]
]

H, inliers = compute_homography(pts_image, pts_plan)

print("Homographie :\n", H)
print("Points valides (RANSAC) :", inliers.ravel())

Homographie :
 [[ 6.73916337e-03 -4.53003790e-02  1.27985312e+01]
 [ 3.23974141e-03 -2.16205477e-02  6.09805545e+00]
 [ 5.37614690e-04 -3.55189304e-03  1.00000000e+00]]
Points valides (RANSAC) : [1 1 1 1]

Pour interférence.

In [ ]:
import torch 
import torch.nn as nn

class LSTM(nn.Module):
    def __init__(self, input_size, hidden_size,num_layers):
        super().__init__()
        self.lstm=nn.LSTM(input_size, hidden_size,num_layers=num_layers,batch_first=True)
        self.fc=nn.Linear(hidden_size,)